# -*- coding: utf-8 -*-
"""Copy of Data Pre-processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16V84S7zW0UVxcU8bNncAl4Bqx3CqfxWv

# Data Preprocessing Tools

## Importing the libraries
"""



import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_excel('/content/Data.xlsx')
y = dataset.iloc[:, -1].values
X=dataset.iloc[:,:-1].values

dataset.describe()

import seaborn as sns

# Assuming 'df' is your DataFrame and 'column_name' is the column you want to check
sns.boxplot(x=dataset['Salary'])
plt.show()

print(X)

print(y)

"""## Taking care of missing data"""

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

print(X)

"""## Encoding categorical data

### Encoding the Independent Variable
"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
#X = ct.fit_transform(X)

print(X)

"""### Encoding the Dependent Variable"""

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

print(X_train)

print(X_test)

print(y_train)

print(y_test)

"""## Feature Scaling"""

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

print(X_train)

print(X_test)